### ISSUE TITLE
Race condition bugs

### ISSUE THREAD

**Issue by gtfierro** [daniellengyel/xbos_services_getter#2]
I'm concerned about lines like this: https://github.com/daniellengyel/XBOS/blob/master/services/meter_data_historical/server.py#L189-L194

Isn't server state shared for every request? If you have two concurrent requests here, then you can potentially have an incorrect windowsize/etc used because the properties are being set on the server object rather than on the request object.

Consider the following sequence of events

- client 1 requests data from 2018-01-01 to 2018-01-08, 15min interval, MEAN
- server sets `self.windowsize`, `self.start` etc in `get_parameters` for client 1
- while the server is doing that, client 2 requests data from 2018-12-01 to 2018-12-08, 5min interval, MIN
- server sets `self.windowsize`, `self.start` etc in `get_parameters` for client 2
- server calls `get_meter_data` for client 1, but the parameters are all for client 2.

I think this goes away if you remove threading so that there can only ever be one executing request on the server, but that will of course limit concurrent usage

**Comment by gtfierro** [comment]
@moustafa-a for your interest

**Comment by moustafa-a** [comment]
Pranav updated the meter_data_historical service to not use server objects, so this should be resolved.
